const MAX_LIST_PREMIUM = 50
const MAX_LIST_FREE = 10

const MAX_HABIT_PREMIUM = 50
const MAX_HABIT_FREE = 10

const MAX_TASK_PREMIUM = 50000
const MAX_TASK_FREE = 10000

// In Days, server store history for 90 days but cap is on fetching it
const MAX_HABIT_HISTORY_PREMIUM = 90
const MAX_HABIT_HISTORY_FREE = 30

export { MAX_LIST_PREMIUM, MAX_LIST_FREE, MAX_HABIT_PREMIUM, MAX_HABIT_FREE, MAX_TASK_PREMIUM, MAX_TASK_FREE, MAX_HABIT_HISTORY_PREMIUM, MAX_HABIT_HISTORY_FREE }